### ISSUE TITLE
Instance handling problems in vss-tools

### ISSUE THREAD

**Issue by erikbosch** [GENIVI/vss-tools#54]
This is a follow up to https://github.com/GENIVI/vehicle_signal_specification/issues/265

As of now there seems to be 3 issues/limitations that better shall be fixed.

- If you have a branch `A` and then a signal `AB` then it is treated as `A.B` by tooling. See e.g. how `AxleCount` gets represented as `Vehicle.Chassis.Axle.Row1Count` and `Vehicle.Chassis.Axle.Row2Count`
- Currently signals within instantiated branch needs to be defined directly after the branch to be correctly generated, otherwise they will be ignored or not correctly generated. (Not a problem in current VSS model)
- Currently instantiations cannot be redefined, to e.g. change number of axles or number of seat rows compared to default.

A PR to be address this is being prepared

**Comment by erikbosch** [comment]
Test file used. The assumption is that this shall be a valid file.

```

- Vehicle:
  type: branch
  description: Vehicle branch.
  
- Vehicle.A:
  type: branch
  instances:
    - Row[1,4]
  description: A branch.
  
# Bug #1 - Previously we checked against "A", not "A."  
# Make sure that AB is not represented as A.B
# This issue can be seen for AxleCount in VSS
- Vehicle.AB:
  datatype: uint8
  type: sensor
  description: A.B

# Bug #2 - Previously we stopped searching for instance members as soon as we found 
# first item not matching the current branch. Now We keep searching
- Vehicle.A.E:
  type: branch
  instances:
    - Pos[1,3]
  description: A.E branch.
  
- Vehicle.A.E.F:
  datatype: uint8
  type: sensor
  description: A.E.F
  
- Vehicle.C:
  type: branch
  description: C branch.
  
- Vehicle.A.B:
  datatype: uint8
  type: sensor
  description: A.B
  
- Vehicle.C.D:
  datatype: uint8
  type: sensor
  description: C.D

# Bug/Improvement #3 - previously we did not allow re-instantiation. Now a new instantiation will overwrite the old one
# Redefine A - we only want 2 rows
- Vehicle.A:
  type: branch
  instances:
    - Row[1,2]
  description: A branch.
  
#Redefine A.E - We only want 2 pos
- Vehicle.A.E:
  type: branch
  instances:
    - Pos[1,2]
  description: A.E branch.
```
And that this is the wanted result:

```
$ more test.csv
Signal,Type,DataType,Deprecated,Complex,Unit,Min,Max,Desc,Enum,Id,Instance
Vehicle,branch,,,false,,,,Vehicle branch.,,ccc825f94139544dbb5f4bfd033bece6,
Vehicle.A,branch,,,false,,,,A branch.,,f799e5c67a9d566b89e58e38a5955c18,
Vehicle.A.Row1,branch,,,false,,,,A branch.,,5442fcf315f45202bf0519eec4231ea3,
Vehicle.A.Row1.E,branch,,,false,,,,A.E branch.,,ed8cf42f8c7e5d4189a22895bdfabf3d,
Vehicle.A.Row1.E.Pos1,branch,,,false,,,,A.E branch.,,af9c30b21ae55894b473f170b771a8e8,
Vehicle.A.Row1.E.Pos1.F,sensor,uint8,,false,,,,A.E.F,,dc57a3e42ec25101b4db626eb03031bf,
Vehicle.A.Row1.E.Pos2,branch,,,false,,,,A.E branch.,,aa7a1b702e1a5a118f926bd7eea72038,
Vehicle.A.Row1.E.Pos2.F,sensor,uint8,,false,,,,A.E.F,,b4693c6e74685f18ab0f63b156ed0793,
Vehicle.A.Row1.B,sensor,uint8,,false,,,,A.B,,0bb3f5a1382654b0a713ffecd7a9e7c4,
Vehicle.A.Row2,branch,,,false,,,,A branch.,,5f5ccf7dc45d5d8ca2d3c9d47be60bc8,
Vehicle.A.Row2.E,branch,,,false,,,,A.E branch.,,935e04355ac653f3bb922a6755175739,
Vehicle.A.Row2.E.Pos1,branch,,,false,,,,A.E branch.,,330d7c27f55d5c04b99063fb9b5774ef,
Vehicle.A.Row2.E.Pos1.F,sensor,uint8,,false,,,,A.E.F,,ffa41e425bf8589fa00cc8b0e46be96a,
Vehicle.A.Row2.E.Pos2,branch,,,false,,,,A.E branch.,,25ece4a4f99e5f84818dd8b4c3308570,
Vehicle.A.Row2.E.Pos2.F,sensor,uint8,,false,,,,A.E.F,,9cd31845672d5e31adc02e54066f4249,
Vehicle.A.Row2.B,sensor,uint8,,false,,,,A.B,,283818c9244f58d48b81e70c054f8ba5,
Vehicle.AB,sensor,uint8,,false,,,,A.B,,2876ef2ba5375db9862802c828cb067a,
Vehicle.C,branch,,,false,,,,C branch.,,300d4bad09985e579a58905bc30c7353,
Vehicle.C.D,sensor,uint8,,false,,,,C.D,,1a8c96ee6f745788b52d2de0f67d5717,
```
